# Generated by Django 3.0.4 on 2020-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200313_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='beers',
            field=models.ManyToManyField(to='groups.Beer'),
        ),
    ]
