# Generated by Django 3.0.4 on 2020-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['beer_name']},
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='image',
            new_name='beer_label',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='name',
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_abv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_description',
            field=models.CharField(default='beer description', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_ibu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_style',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery_city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery_state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
