# Generated by Django 3.0.4 on 2020-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20200327_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
