# Generated by Django 3.0.4 on 2020-03-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20200327_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_style',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery_state',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
